### ISSUE TITLE
Configure Microsoft Office macro settings

### ISSUE THREAD

**Issue by dcaddick** [govau/desktop.gov.au#127]
Where can I find more information on this please?

From this article:
https://desktop.gov.au/blueprint/essential-eight-maturity.html#configure-microsoft-office-macro-settings

> Macro executions are natively logged to the ‘TrustRecords’ entry in the Windows 10 registry, including the time and location that the macro is run. Defender for Endpoint also centrally stores Endpoint Detection & Response (EDR) logs for all Windows 10 blueprint devices, which includes the execution of macro-enabled documents and resulting behaviours (such as attempts to make Win32 API calls).

What I am very keen on is finding exactly how this can be done at scale?
Can we get more details on *exactly* how this is enabled please

Thanks,
Dave Caddick

**Comment by zedzedzed** [comment]
Just going to close this as it looks like your query has been responded to. Feel free to reopen or create a new ticket otherwise.
