### ISSUE TITLE
TrustRecords keys are not created in registry when Trusted Documents are disabled for an Office application

### ISSUE THREAD

**Issue by aminalll** [govau/desktop.gov.au#134]
In my testing TrustRecords keys are not created in the registry when Trusted Documents are disabled for an Office application. 

Would be great if someone else could confirm this as well to back me up :).

TrustRecords values should be stored in HKEY_CURRENT_USER under '\Security\Trusted Documents\TrustRecords' for a particular Office application (e.g. Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\16.0\Word\Security\Trusted Documents\TrustRecords).

The [ACSC Microsoft Office macros guide](https://www.cyber.gov.au/acsc/view-all-content/publications/microsoft-office-macro-security) and [this blueprint](https://desktop.gov.au/blueprint/client-devices.html#office-macro-hardening) state that Trusted Documents should be disabled so I believe that the following statement should be removed from the blueprint [here](https://desktop.gov.au/blueprint/essential-eight-maturity.html#configure-microsoft-office-macro-settings):

>Macro executions are natively logged to the ‘TrustRecords’ entry in the Windows 10 registry, including the time and location that the macro is run.

Of course, with this statement removed it might mean that Defender for Endpoint (and the associated increased cost from E3) is the only feasible mechanism to log allowed macro transactions as required by the E8.

**Comment by zedzedzed** [comment]
Just going to close this as it looks like your query has been responded to. Feel free to reopen or create a new ticket otherwise.

**Comment by oobedan** [comment]
@aminalll @zedzedzed trust records has been specifically removed in pull requrest to avoid confusion for users blocking trusted documents based on this feedback. The update is in Develop branch but hasn't been merged onto the live website as yet. The recommendation is to do the monitoring via Defender for Endpoint, if you don't have defender for endpoint licensed then would require something like Sysmon or third-party (which is out of the scope of the blueprint configuration).

**Comment by zedzedzed** [comment]
I believe @oobedan was referring to pull request #139
