### ISSUE TITLE
Azure AD PIM Scopes

### ISSUE THREAD

**Issue by pl4nty** [govau/desktop.gov.au#170]
> When deploying the RBAC model in Azure, there are two scopes where access can be granted.

Is it worth mentioning the granular scopes? eg [PIM roles](https://docs.microsoft.com/en-us/azure/active-directory/privileged-identity-management/pim-how-to-add-role-to-user#assign-a-role-with-restricted-scope) scoped to [Administrative Units](https://docs.microsoft.com/en-us/azure/active-directory/roles/administrative-units).

**Comment by SamBH** [comment]
Hi @pl4nty - Pull Request #173 has been created to update available PIM scopes in the Platform Design.

Thank you for your feedback.

**Comment by oobedan** [comment]
Closing as this has been addressed under #173.
