### ISSUE TITLE
Intune Configuration - OMA-URI in CSP's contain a space

### ISSUE THREAD

**Issue by ob1kxb** [govau/desktop.gov.au#178]
Almost all OMA-URI contain a linefeed between the path and the name of the value. This will make the the setting to fail when applied if you have copied/pasted the OMA-URI into the Intune tenant configuration profiles:
https://desktop.gov.au/blueprint/abac/intune-configuration.html#configuration-profiles
for instance:
![image](https://user-images.githubusercontent.com/98939783/152295561-63296bf2-429c-42f8-914e-dc52decc92fa.png)

will copy/pasted as:
./Device/Vendor/MSFT/Policy/Config/TimeLanguageSettings/ ConfigureTimeZone

Resulting in a Event error 404 in the Event Log "DeviceManagement-Enterprise-Diagnostics-Provider:
MDM ConfigurationManager: Command failure status. Configuration Source ID: (9ACE0B9C-26B2-4918-AD01-0384CFE8C463), Enrollment Name: (MDMDeviceWithAAD), Provider Name: (Policy), Command Type: (Add: from Replace or Add), CSP URI: (./Vendor/MSFT/Policy/Config/ApplicationManagement/ RequirePrivateStoreOnly), Result: (The system cannot find the file specified.).

Suggestion is to modify the OMA-URI's in the configuration profiles pages and remove the linefeed

**Comment by oobedan** [comment]
Sorry, linefeed was wrapped for table friendliness. Will correct this. Thanks for the feedback.

**Comment by oobedan** [comment]
This has been fixed in #188, closing this one.
