### ISSUE TITLE
Anonymous access to Teams Meetings

### ISSUE THREAD

**Issue by StefanDavenport** [govau/desktop.gov.au#187]
I'm seeking clarification on the configuration defined in the DTA Blueprints as it relates to anonymous access to Teams Meetings.  The Teams "Organization wide configuration" design decision table states "Allow only dta.gov.au and deny sharing to external users. This will prevent users from setting up meetings with users that are not setup as a Guest of the Agency" for External Users, however the ABAC Teams Meeting Policy refers to the default "Global" policy.  This policy has "Let anonymous people join a meeting" enabled however this configuration item is not listed in the ABAC table of settings.

Could you please advise on the defined configuration for the Blueprint?

![image](https://user-images.githubusercontent.com/100643246/156077838-d2b94c53-6b24-41bb-acba-d6915d980570.png)

**Comment by oobedan** [comment]
Hi @StefanDavenport. This setting appears to be missing from the ABAC (we will update this next release). Anonymous join is recommended to be disabled as a starting point as per the design (recommends guest or use of external accounts). Agencies should risk assess the use of anonymous join depending on their requirements (e.g 3rd party does support the use of Microsoft accounts).

**Comment by oobedan** [comment]
This has now been updated in the 365 ABAC. Closing issue
