### ISSUE TITLE
Formatting/information issue GRANT - Terms of use

### ISSUE THREAD

**Issue by ScottOfford** [govau/desktop.gov.au#195]
There appears to be some missing information in the [GRANT - Terms of use](https://desktop.gov.au/blueprint/abac/conditional-access-policies.html#grant---terms-of-use) section under Conditions > Locations. It appears the configuration for Locations is missing and the heading is misrepresenting the Client apps section.

Currently reads:
![image](https://user-images.githubusercontent.com/67613661/160762035-98daacce-8632-4828-8204-748935ee3e44.png)

Should possibly read:
![image](https://user-images.githubusercontent.com/67613661/160762267-d3635694-446c-47b7-a0b6-ceffe3f66242.png)

**Comment by oobedan** [comment]
Thanks @ScottOfford. Update merged into develop. Will be pushed to Main/production on next sync.
