### ISSUE TITLE
ABAC - Intune Software Updates - Windows

### ISSUE THREAD

**Issue by FranklyFrivolous** [govau/desktop.gov.au#204]
Appears the options have changed within the configuration options in endpoint manager.

There are no longer servicing channels 

_Update ring settings: Servicing channel: Semi-Annual Channel_

Raised a case with MS, they confirmed it had been deprecated. DTA may need to look into the new feature

https://docs.microsoft.com/en-us/mem/intune/protect/windows-update-settings

**Comment by oobedan** [comment]
Thanks @FranklyFrivolous will look into it. Sorry for delay in responding.

**Comment by oobedan** [comment]
@FranklyFrivolous we base the design off the latest ACSC hardening guide is for 21h1 which is still on the old servicing channels, however we would recommend 21h2 which introduces GA channel. Updating to reflect, just need to confirm approach with the ACSC.

**Comment by oobedan** [comment]
Pull request #212 has been raised to merge in latest updates removing SAC guidance..

**Comment by oobedan** [comment]
CLosing as addressed with merge  #212
