### ISSUE TITLE
Incorrect Template

### ISSUE THREAD

**Issue by CEJ2022** [govau/desktop.gov.au#210]
Hello, Under the Adopt and Engage Phase of the DTA Business change guide, the wrong template is showing under “Assess [change readiness](https://desktop.gov.au/assets/files/pdf/dta-change-impact-assessment.xlsx)”
That is the Change Impact Assessment and **NOT** the Change Readiness Assessment. Can you please update it and send me a copy of the correct template?

Thanks!

**Comment by oobedan** [comment]
Hi @CEJ2022. Have referred this issue to the DTA. Will advise.

**Comment by CEJ2022** [comment]
Fabulous! Thanks :-)

**Comment by oobedan** [comment]
Updated hyperlink under PR #218
