### ISSUE TITLE
Missing Powershell Script

### ISSUE THREAD

**Issue by egogenesic** [govau/desktop.gov.au#50]
A powershell script referenced by the ABAC guide doesn't seem to have been provided.

ABAC > Intune Applications > Defender Advanced Threat Protection (ATP) registry recommendations

The application configuration references a powershell script (DefenderATP.ps1) that should be deployed however the file contents are not available

https://desktop.gov.au/blueprint/abac/intune-applications.html#defender-advanced-threat-protection-atp-registry-recommendations

**Comment by zedzedzed** [comment]
Thank you for reporting, this will soon be merged to prod.
