### ISSUE TITLE
Missing Sensitivity Label configuration details

### ISSUE THREAD

**Issue by egogenesic** [govau/desktop.gov.au#51]
The ABAC > Office365 >Security and Compliance > Sensitivity Labels section lists the configuration details for the Unofficial, Official, Official Sensitive and Protected labels.

The ABAC > Office365 >Security and Compliance > Sensitivity Label Policy section lists 17 labels that should be published (listed below) but the configuration details are only provided for 4 of the labels (listed above).

https://desktop.gov.au/blueprint/abac/office-365.html#sensitivity-label-policy

UNOFFICIAL
OFFICIAL
OFFICIAL Sensitive
OFFICIAL Sensitive ACCESS=Legal-Privilege
OFFICIAL Sensitive ACCESS=Legislative-Secrecy
OFFICIAL Sensitive ACCESS=Personal-Privacy
PROTECTED
PROTECTED ACCESS=Legal-Privilege
PROTECTED ACCESS=Legislative-Secrecy
PROTECTED ACCESS=Personal-Privacy
PROTECTED CAVEAT=SH CABINET
PROTECTED ACCESS=Legal-Privilege CAVEAT=SH CABINET
PROTECTED ACCESS=Legislative-Secrecy CAVEAT=SH CABINET
PROTECTED ACCESS=Personal-Privacy CAVEAT=SH CABINET

**Comment by zedzedzed** [comment]
Thank you for reporting, this will soon be merged with prod.
