### ISSUE TITLE
Use of CMTrace

### ISSUE THREAD

**Issue by noreilly-ccx** [govau/desktop.gov.au#54]
Within the cloud only and hybrid ABAC the application CMtrace is deployed. The abac is missing the deployment script and may not be applicable in the cloud only scenario as the CMTrace application exe is from a Configuration manager install. 

Also as of 1909 I believe CMTrace is being replaced by OneTrace.

**Comment by zedzedzed** [comment]
The missing scripts were added in #69 but the use of CMTrace has been removed from the blueprint (#115) as not useful for the majority of our users.
