### ISSUE TITLE
Error in Intune Configuration profile TimeZoneEST

### ISSUE THREAD

**Issue by CinBrennan** [govau/desktop.gov.au#58]
OMA-URI string states the correct value is: ./Device/Vendor/MSFT/Policy/TimeLanguageSettings/ConfigureTimeZone but it should be: ./Device/Vendor/MSFT/Policy/Config/TimeLanguageSettings/ConfigureTimeZone

**Comment by zedzedzed** [comment]
This should be resolved and will be rolled out shortly. Thank you
