### ISSUE TITLE
ABAC has the following spelling mistakes

### ISSUE THREAD

**Issue by tebbsynz** [govau/desktop.gov.au#65]
1 - Example as-built-as-configured (ABAC) documents detail specific technical configurations, **wich** include
2 - Blueprint **aretfacts** provide guidance on integration between MECM
3 - Agencies that implement the Blueprint at a Protected level will need to configure **some some** components
4 - Protected **email email** must be sent and received over GovLink
5 - Standard operating **pocedures**
6 - ACSC strategy | Solution | **Jusitification** | Maturity level
7 - Workstation configuration is stored in Intune (**AutoPilot** rebuild)

**Comment by martincaddick** [comment]
@tebbsynz  Can you tell us which files those typos are in?
1.
2.
3. overview.md
4. overview.md
5.
6.
7.

**Comment by tebbsynz** [comment]
@martincaddick - Apologies not not being clear. They are all in the Blueprint Solution overview page and I have bolded the specific word, so it may be possible to search on this.
https://www.desktop.gov.au/blueprint/overview.html

1 - https://www.desktop.gov.au/blueprint/overview.html#where-to-start - Where to start
Example as-built-as-configured (ABAC) documents detail specific technical configurations, **wich** include

2 - https://www.desktop.gov.au/blueprint/overview.html#design-considerations - Design considerations then Implementation type
Blueprint **aretfacts** provide guidance on integration between MECM

3 - https://www.desktop.gov.au/blueprint/overview.html#design-considerations - Design considerations then Agency classification
Agencies that implement the Blueprint at a Protected level will need to configure **some some** components

4 - https://www.desktop.gov.au/blueprint/overview.html#govlink - GovLink
Protected **email email** must be sent and received over GovLink

5 - https://www.desktop.gov.au/blueprint/overview.html#security - Security
Standard operating **pocedures**

6 - https://www.desktop.gov.au/blueprint/overview.html#essential-eight-maturity - Essential eight security
ACSC strategy | Solution | **Jusitification** | Maturity level

7 - https://www.desktop.gov.au/blueprint/overview.html#essential-eight-maturity - Essential eight security and the very last paragraph on the page
Workstation configuration is stored in Intune (**AutoPilot** rebuild)

I hope this helps

**Comment by martincaddick** [comment]
@tebbsynz Yeah now that makes sense. I can see what you mean in the html page however when I go back to the overview.md file 'wich' is actually correct in that it is spelt 'which'. I went straight to the .md file and searched the repo for the typos and only found 'some some' and 'email email'. We'll need DTA to fix it.
Cheers

**Comment by zedzedzed** [comment]
Thank you for raising them. Some of these were fixed in `develop` and are waiting to be merged into production this week.

**Comment by zedzedzed** [comment]
The rest were fixed with https://github.com/govau/desktop.gov.au/commit/a868eb841241c43fae6915a99a2ab11d12bc5225
