### ISSUE TITLE
Guest invite settings | Configuration options outdated

### ISSUE THREAD

**Issue by eBentl** [govau/desktop.gov.au#76]
The 'Guest invite settings' section under 'Azure Active Directory > Users > User settings > External collaboration settings' has changed since the ABAC was written.

I believe the correct configuration under the new options is:
Guest invite restrictions: Only users assigned to specific admin roles can invite guest users

![image](https://user-images.githubusercontent.com/43974241/124704897-2c571800-df38-11eb-8264-9ec32bc7e175.png)

Additionally 'Enable Email One-time passcode for guests' has moved from this area to:
'Azure Active Directory > External Identities > All identity Providers'
- Configured identity providers
-- Email one-time passcode (Preview)
--- Enable Email One-time passcode for guests: 'No'

**Comment by zedzedzed** [comment]
Thank you for raising this. We have addressed it in the above change.
