### ISSUE TITLE
Essential Eight Maturity Model updated July 2021

### ISSUE THREAD

**Issue by troyphil** [govau/desktop.gov.au#84]
Essential Eight Maturity Model has had significant updates in July 2021 (refer https://www.cyber.gov.au/acsc/view-all-content/publications/essential-eight-maturity-model and https://www.cyber.gov.au/acsc/view-all-content/publications/essential-eight-maturity-model-faq).

Definitely requires update to summary at https://desktop.gov.au/blueprint/overview.html#essential-eight-maturity, and may drive wider updates.

**Comment by zedzedzed** [comment]
Hi Troy, we have been working to incorporate the changes to the July E8 Maturity Model and expect the next release will be inline with the changes. We also hope to expand upon the material we already have that may provide more detail/clarity. Many of the pull requests have included part of this work. Some open PRs are relevant to the updated E8 so feel free to join the conversation if you want.
